// Ten-step narrative copy (en): chip badge / title / panel body HTML; dotNames = bottom nav labels.
// Camera positions and structure live in src/story/stages.js; edit English copy here only.
// Terms in the body get dotted underlines automatically (ui/terms.js);
// hard-coded counts are enforced by scripts/check-narrative.mjs.

export const stages = [
 {chip:'STEP 0 · Overview', title:'The true shape of a complex project',
  body:`<p>Picture a piece of software on the scale of <b>Blender or VS Code</b>. Its code was never a single tree — it is <b>an entire forest growing on one plot of land</b>: two dense <b>domain trees</b> (the editing core and the user interface) carry the product itself, while <b>fourteen cross-cutting trees</b> cut sideways through everything — from the classics of architecture, performance, permissions, and gating, to observability, concurrency, and fault tolerance, on to compatibility, security, privacy, i18n, collaboration, billing, and multi-tenancy.</p>
  <p>Three kinds of trouble hide in this forest. Requirements weld nodes from different trees together into <span class="r">red tangles</span>. Some nodes are born as a pair, held by a <span class="mg">magenta gravity</span> nothing can separate. The <span class="gh">cyan rings</span> on the ground are repository boundaries — the big ring encloses the whole workspace, and the small dashed ring at each tree's foot says: <b>every tree can become its own repository or sub-repository</b>. And drifting outside every ring are a few <span class="gh">ghost roots</span> — for some code, the real answer isn't in the code at all.</p>
  <p>This model tries to answer one central question of the AI era: <b>at what point does a project become too complex for AI to follow — and what can we do about it?</b></p>
  <div class="hint">👁 <b>What to watch</b>: drag to rotate and take in the whole scene first; for an automatic orbit, click “⟳ Auto-rotate” in the bottom-left or press Space (static by default — nothing plays on its own). Red lines are accidental coupling, magenta beams are essential coupling, and the dashed lines reaching outside the ring are truth outside the repo — each gets its own step later. Words with a dotted underline pop up an explanation on hover.</div>`},
 {chip:'STEP 1 · One Tree', title:'One tree = one perspective; the root = SSOT',
  body:`<p>Start with a single tree. Its root is the <span class="g">SSOT</span> (single source of truth): the final authority behind every decision made from this perspective. <b>The perspective decides how the tree grows</b> — the editing-core tree in front of you grew along the perspective of “data model and consistency”: scene graph, dependency graph, datablocks, modifier stack, drivers, undo history, file format… This is the main text of a tool like Blender or VS Code.</p>
  <p><b>Domain trees are born deeper and denser than cross-cutting trees</b> — this one is already five levels deep with fifty-odd nodes. That isn't sprawl; it's domain complexity: the product's value simply has this shape. It can't be removed, and it shouldn't be.</p>
  <ul>
  <li><span class="g">The golden root</span>: <b>never let AI write here unsupervised</b> — tilt the root a little, and the whole tree tilts with it;</li>
  <li>The tree-colored skeleton: AI may work here, but structural changes need a human gatekeeper;</li>
  <li><span class="gr">Green-rimmed leaves</span>: <b>hand these to AI with confidence</b> — their meaning is pinned down by the layers above, and a mistake can't reach the root.</li>
  </ul>
  <div class="hint">👁 <b>What to watch</b>: hover over any node to see its role and its “meaning count”. Depth is not the problem — as long as every node means exactly one thing.</div>`},
 {chip:'STEP 2 · Many Trees', title:'Domain trees × cross-cutting trees = a force field of conflicting constraints',
  body:`<p>Pull the view back: sixteen trees, in two kinds.</p>
  <ul>
  <li><b>Two domain trees</b> (<b style="color:#d9e650">Edit Core</b>, <b style="color:#ff7fb2">UI</b>): deep and dense. That is domain complexity — Blender's dependency graph, VS Code's extension host; the problem itself is this hard, whoever builds it;</li>
  <li><b>Fourteen cross-cutting trees</b>: shallow, but each runs sideways through the entire product, each enforcing one constraint — and the constraints charge each other a price —
    <b style="color:#5b8cff">Architecture</b> adds layers for extensibility, and <b style="color:#ff9e4d">Performance</b> pays first; <b style="color:#b28dff">Permissions</b> without a general model can never claw the ad-hoc patches back; every switch in <b style="color:#3ad6c5">Gating</b> is a forked universe;
    <b style="color:#7ee08a">Observability</b> wants to see everything, <b style="color:#dcc98a">Privacy</b> wants it covered; <b style="color:#d9a05f">Concurrency</b> wants parallel, consistency wants serial; every retry in <b style="color:#ff795c">Fault&nbsp;tolerance</b> interrogates idempotency;
    <b style="color:#6f6fe8">Compatibility</b> holds a veto over every change; <b style="color:#54a8d9">Security</b> treats every input as an enemy; <b style="color:#d97bff">i18n / accessibility</b> cuts through every string and every control;
    <b style="color:#9fdf5f">Collaboration</b> demands that everything be mergeable; <b style="color:#b0e04d">Billing</b> cannot lose a single record; <b style="color:#9a5fd0">Multi-tenancy</b> makes every cache key carry one more dimension.</li>
  </ul>
  <p>There is no “optimal for everyone at once”. What we call project evolution is the domain trees finding a way to grow upward through these conflicting constraints.</p>
  <div class="hint">👁 <b>What to watch</b>: under each tree's label are its perspective and its price. Notice that not a single line connects the trees yet — this is the ideal state, and it is about to be broken.</div>`},
 {chip:'STEP 3 · Tangles', title:'Requirements weld the trees together',
  body:`<p>A requirement never stays politely inside one tree. Take a single feature, “batch-export scene reports”: it steps into six trees at once — <b>Performance</b> (batching, caching), <b>Permissions</b> (row-level filtering), <b>Gating</b> (canary), <b>Architecture</b> (service boundaries), <b>Billing</b> (does an export count as usage?), and <b>Privacy</b> (PII in the report).</p>
  <p>Click “▶ Play” on the case bar and the red lines appear one by one — even the domain trees get dragged in: <span class="dim">macro recording captures the behavior of an experiment branch; undo snapshots get reordered by batched writes; the plugin sandbox borrows API auth; a cache key forgets its tenant prefix; log sampling drops hardest exactly during a retry storm; the right to be forgotten chases into every cache layer…</span> Welded nodes turn red and grow <span class="r">polysemy halos</span>: one more ring is one more meaning to carry.</p>
  <p>A cruel regularity: <b>the stronger a capability's global reach (permissions, gating, caching, tenant isolation), the more red lines it creates</b>. The capabilities most valuable to users are precisely the biggest sources of entanglement. How dense do the red lines get once all fourteen cross-cutting trees light up? Light them all and see for yourself.</p>
  <div class="hint">👁 <b>What to watch</b>: click “▶ Play” to reveal the cases one by one (nothing plays until you click); hover over any red line or red node for the real-world story behind it. Drag the progress bar to freeze on any case; click “⚡ Show all” to light everything at once — once shown, the scene stays put, no carousel.</div>`},
 {chip:'STEP 4 · Gravity', title:'Some nodes were never meant to be apart',
  body:`<p>Entanglement comes in two kinds. The red lines of the previous step are <b>accidental coupling</b>: a requirement happened to pass through and tied two unrelated nodes together — a different design could, in principle, untie them. The other kind cannot be untied: <span class="mg">essential coupling</span> — <b>the problem itself requires these two nodes to stay together</b>. This forest holds <b class="mg">12 pairs</b>; click “▶ Roll call” to meet them one at a time:</p>
  <div id="grav-case-slot"></div>
  <p>Grouped by <em>why they can't be pulled apart</em>, they grow in three patterns (click any pair to jump straight to it):</p>
  <div id="grav-groups"></div>
  <p>Look — these nodes are <b>breaking out of their trees' shapes and drawing toward each other</b>: the magenta gravity beams. Trees can be pulled apart; these pairs cannot. Force them into layers and all you do is stretch the branches that connect them (you can try it yourself at the “Surgery” step). <b>Telling accidental from essential is the precondition of all governance</b>: the accidental can be dissolved; the essential can only be acknowledged.</p>
  <div class="hint">👁 <b>What to watch</b>: after you click “▶ Roll call”, one pair is called every 5 seconds (nothing plays until you click) — the called beam thickens and brightens, both end nodes breathe in sync, a nameplate rises at the midpoint, and the other beams step back. You can also click any pair in the list to freeze on it. Hover over a beam for the full story, and note the branches being bent.</div>`},
 {chip:'STEP 5 · Off-Graph Truth', title:'Ghost roots: the truth is not in the text',
  body:`<p>However messy tangles and gravity get, at least they are <b>drawn on the graph</b> — attention budget is expensive, but spend enough of it and you can read them. The third kind is the worst: <b>the truth that decides how the code behaves has left the repository</b>.</p>
  <p>The <span class="gh">cyan ring on the ground is the repository boundary</span>: inside it is every piece of text AI can read. And the boundary is <b>nested</b> — each tree has a small dashed ring at its foot: <b>every tree can be an independent repository, or a sub-repository inside the big one</b>. Where to draw the boundary is an engineering choice: the smaller you cut, the less text AI has to read at once — but every dependency that crosses a ring must become an explicit contract, or it becomes the next ghost root.</p>
  <p>The real trouble floats <b>outside every ring</b>. Five <span class="gh">ghost roots</span> are the true sources of truth for certain nodes — and no matter how the boundaries are drawn, they cannot be fenced in:</p>
  <ul>
  <li>👻 <b>DI container</b>: which implementation an interface binds to at runtime is decided by wiring configuration — the calling code simply doesn't show it;</li>
  <li>👻 <b>Event bus</b>: who is listening to an event, and in what order it is handled — only the runtime subscription table knows;</li>
  <li>👻 <b>User disks</b>: whether the file format can change is decided by the hundreds of millions of old files sitting on users' machines;</li>
  <li>👻 <b>Deployment system</b>: which path the program takes is decided by environment variables and configuration;</li>
  <li>👻 <b>Downstream callers</b>: which behaviors of your interface must never change is decided by code outside the ring that depends on it — and you don't even know who they are (Hyrum's Law).</li>
  </ul>
  <p>The two failure modes differ completely in lethality: polysemy inside the graph makes AI <b>edit wrong</b>; truth outside the graph makes AI <b>edit the text “right” — while it is the real world that breaks</b>. The compiler doesn't complain, and tests usually don't either (mocks conveniently fence the truth out); the damage surfaces in production days later. The error signal never makes it back into the loop — not even small, careful iterations can save you.</p>
  <p>There is exactly one test: <b>given only the text inside the repository, can AI answer “what is this interface actually bound to at runtime”?</b> If it can't, that's a ghost root — and the test holds at every boundary level: whole workspace, standalone repository, or sub-repository, no exceptions.</p>
  <p>Keep your eye on the fifth one. For most products, downstream callers are a marginal risk; but for one family of products — Terraform, Playwright, Sentry, the “bricks built for engineers” — <b>the interface is the product</b>, and this ghost root is their lifeline. In the final step, “Tree of Trees”, you will see how it grows into the <b>meta-root</b> of an entire family of systems.</p>
  <div class="hint">👁 <b>What to watch</b>: hover over the ghost roots and the dashed lines — each one is a complete accident report. The nodes held by dashed lines are flickering: their meaning is not theirs to decide.</div>`},
 {chip:'STEP 6 · Collapse', title:'Polysemy vs. the attention budget',
  body:`<p>Fix your eyes on one node: <b>“cache policy”</b>. With all fourteen cross-cutting trees in place, it carries <b>7 meanings</b> at once:</p>
  <ul>
  <li>① The original meaning, from <b style="color:#ff9e4d">Performance</b>: how to trade hit rate against TTL;</li>
  <li>② Plus <span class="r">Permissions</span>: the cache key must encode permission information;</li>
  <li>③ Plus <span class="r">Gating</span>: during a canary, old and new data shapes coexist;</li>
  <li>④ Plus <span class="r">Architecture</span>: the source of truth for TTL lives on another tree;</li>
  <li>⑤ Plus <span class="r">Compatibility</span>: during dual read/write, one key holds two schema versions;</li>
  <li>⑥ Plus <span class="r">Privacy</span>: a right-to-be-forgotten deletion must chase into every cache layer;</li>
  <li>⑦ Plus <span class="r">Multi-tenancy</span>: the key format must carry a tenant prefix — forget it and you have an incident.</li>
  </ul>
  <p>This is natural language's “polysemous word” problem replaying itself in code: one name whose current meaning can only be resolved from context. But the attention budget is finite — the <b>solid lines</b> are what fits into context; the <span class="r">red dashed lines</span> are what doesn't. The moment the meanings that must be held together exceed the budget, disambiguation fails: AI starts hallucinating its edits, and every edit makes things worse.</p>
  <p><b>Collapse is not a slow decline — it is a cliff.</b> The more cross-cutting trees there are, the more meanings every “strong node” carries, and the sooner the cliff arrives. Stack off-graph truth on top, and AI cannot even discover that it no longer understands.</p>
  <div class="hint">👁 <b>What to watch</b>: the AI orb needs to hold 7 context beams at once, but its budget covers only 2 — watch the dashed lines strain and flicker.</div>`},
 {chip:'STEP 7 · Surgery', title:'Seven surgeries: operating on this graph',
  body:`<p>The classic engineering strategies are, at bottom, all surgeries on this very graph. <b>Flip the switches below one by one</b> and watch the semantic entropy fall in the top-right gauge. There are only three ideas: <span class="gr">give each node fewer meanings</span> (TDD, SDD), <span class="am">shrink the set of tangles that must be seen at once</span> (layering, platformization), or <b>slow down how fast new entanglement grows</b> (Loops).</p>
  <p>But two kinds of lesion resist the first five knives entirely. The <span class="mg">magenta gravity pairs</span> — switch on “Layering” and see: stretch the branches as far as you like, they will not let go; only “<span class="g">Fusion</span>” can give them a proper home. And the <span class="gh">cyan ghost roots</span> — their truth is not on the graph at all; only “<span class="g">Explicitation</span>” can bring it back inside the repository (dashed lines turn solid, and the nodes stop flickering).</p>`},
 {chip:'STEP 8 · Laws', title:'Laws of complexity governance in the AI era',
  body:`<div class="formula">Complexity AI can handle ≈ <span class="g">attention budget</span> × <span class="am">structural explicitness</span> ÷ <span class="r">average polysemy per node</span></div>
  <p>Five laws. Each has a <b>live scene</b> somewhere in the final-state picture in front of you — click a card, and the camera takes you there:</p>
  <div id="law-list"></div>
  <div class="quote">Complexity cannot be destroyed — only <b>placed</b>.<br>A good engineering system places polysemy inside the attention budget, and places truth inside the repository boundary —<br>and it can tell the difference: some distances can be stretched open, and some never existed at all.</div>`},
 {chip:'STEP 9 · Tree of Trees', title:'Trees grow into a tree: growth order is system destiny',
  body:`<div id="meta-paths"></div>
  <div id="meta-traits"></div>
  <p>Finally, look at the forest from a different altitude: <b>these trees themselves form a larger tree</b>. No cross-cutting tree appears out of thin air — each grows out of another tree's pain: the interface stutters, and the threading model is forced into writing; incident hunts force observability into existence; only with metrics does anyone dare to canary. <b>“Whose pain you grew from” is “whose child you are”.</b></p>
  <p>Here is the crux: <b>the same set of trees, grown in a different order, becomes a completely different tree of trees</b>. If A comes before B, B must route around the terrain A has already fixed; if B comes first, it is A that gets shaped. Five head-to-head orderings:</p>
  <ul>
  <li><b>Performance before permissions</b>: the cache key carries no permission bits on day one; when row-level permissions arrive, the whole cache layer is rewritten. <b>Permissions before performance</b>: every path is born permission-checked, clean — but baseline latency runs high, and speed has to be carved out later;</li>
  <li><b>Undo before collaboration</b>: an undo built on single-user history is torn up and rewritten the day multiplayer arrives. <b>Collaboration before undo</b>: undo is born as “undo <i>my</i> operations” — at the price of offline, single-machine use becoming a second-class citizen;</li>
  <li><b>Instrumentation before features</b>: every feature is born measurable and history never has a gap — but once the metric definitions circulate, every dashboard in the company locks them in place. <b>Features before instrumentation</b>: a light, quick start — but events never logged can never be backfilled; by the time you ask “why did retention rise last year”, that history no longer exists;</li>
  <li><b>Compliance before growth</b>: every path is born leaving an audit trail, and a regulator's visit holds no terror — but an experiment culture never grows, and releases come one window per quarter. <b>Growth before compliance</b>: ten experiments a week — but privacy is a patch stapled on by fines, and deletion requests must chase into every layer of instrumentation;</li>
  <li><b>Contract before engine</b>: every implementation works for the promise; anything can be rewritten except behavior — and the ecosystem welds every door shut for you. <b>Engine before contract</b>: travel light and fast — but Hyrum's Law catches up eventually: every observable behavior ends up a promise that nobody ever approved.</li>
  </ul>
  <p>What earns a tree the rank of <b>meta-root</b>? The criterion is single: <b>a dense enough run of one-way-door decisions</b> — the file format, the primary key of the first table, the event-stream definitions, the promise that every step leaves a trail: step through, and there is almost no way back. Gating is the perfect counter-example: a flag is born a two-way door — built to be rolled back — and constrains nobody who comes later; however early it arrives, it never defines the terrain. And one batch of one-way doors can be welded for only one master: the same data model cannot be designed both for “deep” and for “mergeable”; the same pipeline cannot both “leave a trail at every step” and run “ten experiments a week” — among the four meta-roots stands something like an <b>impossible triangle</b>. You get to choose one skeleton; the rest are doomed to grow as prosthetics, and the condition is nearly incurable: remedial work can add features, but it cannot add bones.</p>
  <p>Beyond the four paths lies a fifth destiny: <b>developer building blocks rooted in contract</b> — Terraform, Playwright, Sentry, the “bricks made for engineers”. The first four meta-roots weld their one-way doors inside their own repositories: their own data model, their own first table, their own event stream. A building block's doors are welded <b>outside the ring, by Hyrum's Law</b> — the day the first caller you don't control appears, every observable behavior becomes a promise. Its meta-root is exactly the fifth ghost root from the “Off-Graph Truth” step — <b>downstream callers</b>: a marginal risk for ordinary products, but for building blocks the meta-root itself — and a moving one (cloud APIs change daily; browsers ship monthly). Its main text is experience patches: code like “the API returns 200 but the resource only exists five seconds later” — underivable by reasoning, only earned by stepping on the rake. <b>This is exactly why AI cannot reproduce them</b>: every edge of this tree is one real-world pain-feedback event, the growth rings left by a decade-plus evaluation loop — a single generation pass can print a very convincing snapshot, but it cannot grow rings. In 2023, HashiCorp changed Terraform's license, and within a month the ecosystem forked OpenTofu and carried the whole tree away: when the contract is the root, the root belongs to the ecosystem, not to the company. The contract wears three faces — Terraform's <b>declaration</b>, Playwright's <b>promise</b>, Sentry's <b>convention</b> — three paths, three fates: an enterprise platform; a public good with a missing corner (the Collaboration / Permissions / Multi-tenancy / Billing / Privacy trees simply never grow — the commercial debt is carried by a patron); and an accidental SaaS (convention before contract — the brick happened by accident).</p>
  <div class="hint">👁 <b>What to watch</b>: click “▶ Grow” to start (nothing plays until you click). Golden numbers = growth order; edges = “whose pain it grew from”; dashed lines drop to the dimmed forest below — every node up here is a real tree down there. Switch among the seven paths (the first four are industry archetypes; the block-family three are real products' lives) and watch the same trees grow seven different meta-trees — notice how Playwright's tree is missing a corner from birth. The “growth speed” slider adjusts the pace at any time; ↻ replays it. Hover over any node to see why it grew where it did.</div>`},
];

export const dotNames = ['Overview','One Tree','Many Trees','Tangles','Gravity','Off-Graph Truth','Collapse','Surgery','Laws','Tree of Trees'];
