// Glossary (en): 138 concept entries, popped up when hovering dotted-underlined words.
// TERMS: term → {sub subtitle (origin / expansion), d plain-language explanation};
// register aliases with |. Mirrors zh/terms.js line-for-line — entry-count parity is enforced
// by check-narrative. English matching is case-sensitive with \b word boundaries, so register
// capitalized / plural variants where the copy needs them; avoid over-generic bare words
// (e.g. use "state file", never bare "state").

export const TERMS = {};
function defTerm(names, sub, d) { for (const n of names.split('|')) TERMS[n] = { sub, d }; }

// —— Concepts coined by this model ——
defTerm('SSOT|single source of truth|Single source of truth','Single Source of Truth','One piece of information has exactly one authoritative home; everywhere else references it instead of keeping a copy. A tree’s root is the final authority for every decision made from that perspective — corrupt the root, and the whole tree goes with it.');
defTerm('cross-cutting trees|cross-cutting tree|cross-cutting|Cross-cutting','cross-cutting concern','“Cross-cutting” marks requirements that belong to no single business module yet bind all of them — performance, permissions, release control. They run through the project like rebar, and every module has to accommodate them.');
defTerm('domain tree|domain trees|Domain trees','domain tree','The module system that directly carries product functionality — an editor’s data model, its UI interactions. Its depth and density come from the difficulty of the problem itself, not from bad design.');
defTerm('domain complexity','domain complexity','The complexity inherent in the problem domain: 3D software must handle scene hierarchies and dependency updates, and that difficulty stays no matter who builds it — it is exactly where the product’s value lives.');
defTerm('accidental coupling|Accidental coupling','accidental coupling','Two unrelated modules bound together because one requirement happened to touch both. A different design could untie them — the key difference from essential coupling.');
defTerm('essential coupling|Essential coupling|essential gravity|Essential gravity','essential coupling','The problem itself dictates that two modules change together — “command” and “undo”, say. No design can split them; the only way out is to acknowledge the bond and manage them as one.');
defTerm('ghost root|ghost roots|Ghost roots|Ghost root','ghost root','This model’s metaphor: a node’s true source of truth floats outside the repository — runtime wiring, old files on user disks, deployment configuration, downstream code that depends on you. AI can read the code to the bone and never see it.');
defTerm('truth outside the repo|off-graph truth|Off-graph truth|truth off-graph','truth outside the repo','The information that decides how the code behaves is not in the code text — it lives in the runtime, external systems, or user data. Static reading can never recover it, which is exactly what makes it more dangerous than ordinary coupling.');
defTerm('repository boundary|Repository boundary','repository boundary','The cyan ring: inside it is all the text AI can read statically. Boundaries nest — the big ring encloses the workspace, and each tree may have its own small ring (its own repo). The ghost-root test holds at every level: from ring-interior text alone, can you answer the runtime truth?');
defTerm('sub-repository|sub-repo|sub-repositories|sub-repos','sub-repository','A relatively independent slice of a big repository — a monorepo package, a git submodule. It has its own root and boundary and can build and test alone; the price is that every dependency crossing the boundary must be an explicit contract, or it degenerates into off-graph truth.');
defTerm('attention budget|Attention budget','attention budget','The amount of information AI can hold and weigh at once is finite — a workbench of fixed size. Spread out more than fits on the bench, and mistakes begin.');
defTerm('semantic entropy|Semantic entropy','semantic entropy · a metric coined for this demo','A disorder measure of “how many meanings the average name carries”. The denser the tangles and the more truth floats off-graph, the higher the entropy — and the likelier AI misreads.');
defTerm('polysemy|polysemous','polysemy','One name carrying several meanings at once. Like “Apple” the fruit versus the company, the reader must guess from context — a node referenced by many trees is code’s polysemous word.');
defTerm('disambiguation','disambiguation','Determining which of several possible meanings is meant right now. The more meanings and the more scattered the clues, the higher the cost — exceed the attention budget and it fails.');
defTerm('structural explicitness','structural explicitness','How much of the structure is written down: dependencies visible, wiring readable, conventions documented. The more explicit, the less AI has to guess.');
defTerm('pervasive','','A demand that must run through every module and force alignment — permissions must guard every corner, performance must be fast on every path. Such requirements are pervasive by nature.');
// —— The seven surgeries ——
defTerm('layering|Layering','layering','Cut the system into layers by responsibility; crossing a layer means going through a public interface. Inside a layer, mess is allowed; between layers, the contract rules — the price is one extra formality per crossing.');
defTerm('SDD','Spec-Driven Development','Write down what should happen as an explicit spec first, then let the code implement it. Any node’s meaning can be derived from the spec — AI doesn’t have to read the whole codebase and guess.');
defTerm('spec|Spec|specs','specification','An explicit written agreement on what a piece of code should do. With it, meaning has a single home at the root instead of being scattered through implementation details.');
defTerm('TDD|test anchoring|test-anchored','Test-Driven Development','Write the test first, then the implementation. Tests anchor behavior: whoever edits the code — AI included — breaking existing behavior sets off the alarm at once.');
defTerm('Loops|short loops','short loops · small-step iteration','A rhythm of small, fast steps: each loop does a little, and at the loop’s end you review and clean up whatever new mess this round grew — never letting entanglement quietly pile up overnight.');
defTerm('platformization|platformize|Platformize','platformization','Extract the cross-cutting capabilities everyone needs (permissions, gating, audit) into standalone shared services that all modules call — from “everyone implements their own copy” to “everyone depends on the same root”.');
defTerm('fusion|Fusion|co-location','fusion · co-location','This model’s prescription: admit that two modules cannot be separated, and simply put them in the same module, the same layer — designed together, tested together, one owner. If the distance never existed, stop pretending it does.');
defTerm('explicitation|Explicitation','explicitation','Write the invisible facts that live only in the runtime or the environment back into the repository as text AI can read directly: wiring files, subscription tables, golden-file tests, config schemas.');
defTerm('contract|contracts|Contract','contract','Collapse inter-module dependencies into an explicit interface agreement: both sides trust the interface and never peek at each other’s implementation. As long as the contract holds, either side may rewrite its insides freely.');
defTerm('human-in-the-loop','human-in-the-loop','AI output must pass human review before it ships — no full automation. While entropy sits in the middle zone, this insurance cannot be skipped.');
defTerm('platform tree|Platform tree','platform tree','The tree that grows once cross-cutting capabilities are extracted — the new home of permissions, gating, audit. The other trees stop tangling with each other and depend on its root instead.');
defTerm('AI free zone|free zone','AI free zone','The leaf region whose semantics are pinned down by the layers above: AI can write freely here — mistakes are caught by tests and cannot reach the root.');
// —— Around the ghost roots ——
defTerm('DI container|dependency injection|Dependency Injection|DI','Dependency Injection','Objects don’t create their own dependencies; a “container” assembles them at startup according to configuration. The gain is decoupling; the price is that “who is actually behind this interface” vanishes from the code text — only the runtime knows.');
defTerm('event bus|Event bus','event bus','Modules communicate by broadcasting events: fire and forget. Who listens, in what order they run, whether handling fires new events — none of it shows in the code’s call graph.');
defTerm('subscription table','subscription table','The roster of “which event is watched by whom”, usually alive only in runtime memory. Explicitation means writing it down as code or config the repository can show.');
defTerm('golden-file|golden file|golden files|golden-file test|golden-file tests','golden file testing','Store real-world samples (users’ old project files, say) in the repo as the benchmark; every change must still handle them correctly — sampling the “old world outside the graph” into the graph.');
defTerm('schema|schemas','schema','A machine-checkable “manual” for config or data. Once config is schema’d, mistakes surface at commit time instead of exploding after release.');
defTerm('deployment system|Deployment system','deployment system','The machinery that ships code into each environment: env vars, config, release pipelines. The program’s real behavior is often decided there, not in the code.');
defTerm('environment variable|environment variables','environment variable','Configuration read from the running environment at startup — not in the code text. The same code may take entirely different paths in different environments.');
defTerm('annotation scanning|annotation scans','annotation scanning','The framework scans code annotations at startup and auto-registers the wiring. Convenient to write — but the registration graph vanishes from explicit code, and only the runtime can tell you the whole picture.');
defTerm('inline|inlines|inlining','inline','Remove a level of indirection and embed the implementation directly. A seemingly harmless simplification — but if that indirection was an extension point left for others, inlining welds their door shut.');
defTerm('mock|mocks','test double','A fake object standing in for a real dependency (database, network, container) in tests. Make the fake too clean, and the real world’s problems are fenced out along with it — all-green tests don’t mean the world isn’t broken.');
defTerm('hallucination|hallucinating|hallucinate','hallucination','AI fabricating plausible-looking content when information runs short. Edits after failed disambiguation are usually exactly this: confident, fluent, and wrong.');
// —— General engineering terms ——
defTerm('canary release|canary|Canary','canary release','Ship the new version to a small slice of users first, watch, then widen. Meanwhile both versions are live — and the data may exist in two shapes at once.');
defTerm('Feature Flag|feature flag|feature flags','feature flag','A config-controlled switch deciding who gets a feature. Every flag adds a branch — on and off are two parallel universes, each needing its own verification.');
defTerm('gating|Gating','gating · release control','The whole apparatus controlling who sees a feature and when: feature flags, canary releases, A/B experiments all belong to gating.');
defTerm('row-level security|row-level permissions|row-level filtering','row-level security','Permissions down to individual rows: the same table shows different rows to different users. Every global capability — caching, export, batch jobs — must cooperate with it.');
defTerm('API auth','authentication & authorization','The check that answers “who are you, and what may you do”. API auth is that gate in front of every API call.');
defTerm('masking|data masking|field masking','data masking','Hiding sensitive fields before display or export (blurring a phone number, say). It must happen before the data leaves the controlled boundary — which makes “when exactly do we serialize” a matter of life and death.');
defTerm('serialization|serialize','serialization','Turning in-memory objects into storable, transmittable text or bytes. It is data’s last stop before leaving the program — and the last checkpoint for masking and friends.');
defTerm('lazy loading|Lazy loading','lazy loading','Load or compute only at the moment of first real use. Saves resources — but “when does this happen” becomes hard to predict.');
defTerm('precompute|precomputed|Precompute','precompute','Calculate results ahead of time and store them for instant use. Valid only while inputs hold still — one upstream change (a role definition, say) and everything must be discarded and redone.');
defTerm('TTL','Time To Live','How long a cache entry stays valid: expire, discard, recompute. Where the TTL config lives — and who may change it — directly decides the cache’s real behavior.');
defTerm('cache key|cache keys','cache key','The “street address” used to look up a cache entry. What the key encodes decides which requests share a cached value — design it wrong, and A receives B’s data.');
defTerm('hit rate','hit rate','The fraction of requests served straight from cache. Once it drops, the cache is dead weight and all the pressure lands back on the database.');
defTerm('connection pool|connection pools','connection pool','A pre-built set of database connections reused over and over, avoiding fresh handshakes. Each service sizes its own pool — multiply the services and the database’s total connections explode.');
defTerm('instrumentation|Instrumentation','instrumentation','Probes planted in the code to record user behavior and metrics, feeding analysis and experiment decisions.');
defTerm('A/B testing|A/B experiment|A/B splits|A/B split','A/B testing','Randomly split users into two groups, give each a version, and let the data pick the winner. Experiment parameters must reach deep into the code — often straight through module boundaries.');
defTerm('audit|Audit','audit','Recording “who did what, when” entry by entry, for later investigation and compliance review.');
defTerm('abstraction layer','abstraction layer','A middleman inserted between caller and implementation to absorb change. Each layer buys flexibility and costs a little performance and readability.');
defTerm('specialization','specialization','A fast path hard-wired for one scenario: quick, but generality is gone — change the scenario and you rewrite it.');
defTerm('owner','owner','The person clearly responsible for a piece of code: who designs, who reviews, who answers when it breaks. A core move of fusion is giving each gravity pair a single owner.');
// —— Domain terms of the newer cross-cutting trees ——
defTerm('observability|Observability','observability','Inferring a system’s internal state from its outputs — logs, metrics, traces. It is itself cross-cutting: every module must hand over its own vitals.');
defTerm('distributed tracing|tracing','distributed tracing','Issue every request a passport that each service stamps along the way. Which 8 services did that slow query cross, and where did it stall — this is how you reconstruct it.');
defTerm('structured logging|structured logs','structured logging','Logs written as machine-parsable fields (JSON and friends) instead of free-form sentences. Human readability yields to searchability, aggregation, and masking.');
defTerm('log sampling','log sampling','Record only a fraction of logs when traffic is heavy, to save cost. The risk: incidents strike at traffic peaks — exactly when sampling drops the most.');
defTerm('SLO','Service Level Objective','A quantified promise of “how good the service is” — say, 99.9% of requests within 200 ms. Alerts and error budgets are derived from it.');
defTerm('alerting|alert rules','alerting','Waking a human when a metric crosses its threshold. How well the rules are written decides whether the team finds out before the users do — or from them.');
defTerm('main-thread contract|main thread','main thread contract','The iron law of UI programs: some things may only happen on the main thread (painting), some must never (heavy compute). The price of breach is jank.');
defTerm('lock ordering','lock ordering','Multiple locks must be acquired in one globally agreed order, or two threads each hold one and wait on the other — deadlock. Lock order is an invisible global contract.');
defTerm('backpressure','backpressure','The downstream signalling “slow down” upstream when it can’t keep up. A system without backpressure doesn’t slow under overload — it avalanches.');
defTerm('idempotency|idempotent|idempotency key|idempotency keys','idempotency','Running an operation once or three times gives the same result. With it, retries are safe; without it, a retry is a double charge.');
defTerm('backoff','backoff','Don’t retry immediately — wait longer each time (exponential backoff), or every client retries at once and knocks the barely recovering service down again.');
defTerm('circuit breaker|circuit breakers|breakers','circuit breaker','Too many consecutive failures and it trips: fail fast, stop hammering the ailing dependency, give it room to breathe.');
defTerm('graceful degradation|degradation','graceful degradation','When resources run short or a dependency fails, deliberately shut off the non-essential and protect the core path — at peak, drop recommendations first, keep checkout alive.');
defTerm('fallback|fallbacks|fallback path|fallback paths','fallback','The backup logic taken when the main path fails. The danger: fallbacks are usually old code — rarely exercised, rarely tested, and nobody remembered to wire them into the new permission model.');
defTerm('semantic versioning|semver','semantic versioning','Version numbers as compatibility promises: bump the major to allow breakage, bump the minor to only add. The ecosystem reads this code to decide whether it dares upgrade.');
defTerm('dual read/write|dual read-write','dual read/write','During a data migration, read and write both old and new shapes and cut over gradually. Meanwhile the same data exists in two shapes — and every middle layer must understand both.');
defTerm('schema migration|Schema migration','schema migration','The transformation that upgrades data from the old structure to the new. It must recognize every historical version — the same species of work as file-format migration, in another body.');
defTerm('protocol negotiation|version negotiation','protocol negotiation','Both ends first exchange “how new a version do you speak”, then talk at the highest version both understand. In collaboration, old and new clients coexist — negotiation happens every second.');
defTerm('PII','Personally Identifiable Information','Data that can locate a specific person: names, phone numbers, IPs, behavioral trails. Wherever it flows — logs? caches? analytics? — compliance obligations follow.');
defTerm('right to be forgotten|right-to-be-forgotten','right to be forgotten','A user’s right to have their data fully deleted — “fully” meaning every cache layer, every backup, every log line. One action cutting across every store.');
defTerm('data residency|Data residency|residency','data residency','Some countries require their citizens’ data to stay on domestic soil. Sharding, backup, and disaster-recovery topology gain a new dimension: cut along national borders.');
defTerm('data retention|retention period|retention periods|retention policy','data retention','Rules on how long data may be kept. Observability wants longer (debugging); compliance wants shorter (risk) — the same data wears two countdown clocks.');
defTerm('GDPR','the EU General Data Protection Regulation','One of the world’s strictest privacy laws: minimal collection, the right to be forgotten, cross-border limits, ruinous fines. Take European users’ money, accept its jurisdiction.');
defTerm('RTL','right-to-left','The writing direction of Arabic and Hebrew. Supporting RTL is not flipping text — it is mirroring the whole interface, and the layout system must understand “direction” from day one.');
defTerm('accessibility|a11y|Accessibility','accessibility','Making the product usable by people with disabilities: every control readable by a screen reader (semantic annotation), everything operable without a mouse (keyboard reachability). It is an acceptance criterion, not an option.');
defTerm('i18n|internationalization','internationalization','Making software fit any language and culture: externalized copy, plural rules, date formats, RTL layout. Every hard-coded string is its enemy.');
defTerm('CRDT|CRDTs','Conflict-free Replicated Data Type','A specially designed data structure: many people editing at once, offline included, always merge to one determined result — no central referee needed. The price: the data model must grow by its rules from day one.');
defTerm('operation log|operation logs','operation log','Record every operation, in order, as the official history; current state is just its projection. Collaboration, audit, and replay all grow on this log.');
defTerm('presence|Presence','presence','The live signal of “who else is in this document, where their cursor is, what they selected”. What gives collaboration its warmth — and a traffic amplifier.');
defTerm('offline replay','offline replay','Operations made while offline are recorded locally and replayed in order on reconnect. It shares the “restore the scene” turf with autosave and the undo stack.');
defTerm('entitlement|entitlements|Entitlement','entitlement','The authorization system for “what did this account buy, what may it use”. It is a third, independent judgment beside permissions (may you) and gating (is it on) — yet all three usually crowd into one if.');
defTerm('quota|quotas','quota','Per-account or per-tenant usage caps: calls, storage, concurrency. Where quotas hang and how they are counted turns around and defines the API’s shape.');
defTerm('rate limiting|rate limits|rate-limit','rate limiting','How many requests per unit time before the rest are rejected or queued. The floodgate that keeps the system standing — and the boundary line between pricing tiers.');
defTerm('metering','metering','Recording every unit of usage precisely, for billing. Same pipeline as monitoring metrics, opposite requirements: monitoring may sample; metering may not lose one record.');
defTerm('multi-tenancy|multi-tenant|tenant|tenants','multi-tenancy','One system serving many customers (tenants) whose data, performance, and configuration must be mutually invisible. The tenant dimension seeps into every cache key, every table, every queue.');
defTerm('noisy neighbor|noisy neighbors','noisy neighbor','Under shared resources, one tenant’s heavy load drags everyone else down. Isolation must reach deep into schedulers and resource pools — the data layer alone is not enough.');
defTerm('sharding|shard key|shard keys','sharding','Data too big for one machine gets split across many, cut by a key. Pick the wrong key and the hotspots pile onto one shard; when residency laws arrive, you cut again along national borders.');
defTerm('software supply chain|supply chain','software supply chain','Everything your code depends on: third-party packages, images, build tools. Any link poisoned or hit by a CVE is your vulnerability.');
defTerm('CVE','public vulnerability identifier','The global registry number for a security flaw. The moment a CVE publishes, attackers know exactly when you do — patching is a countdown race, with compatibility promises dragging at your legs.');
defTerm('key rotation','key rotation','Swap keys on a schedule so leaked old keys expire on their own. Prerequisite: an accurate ledger of “who is using which key” — whence the war over the keys’ SSOT.');
// —— Tree of Trees (STEP 9) ——
defTerm('tree of trees|Tree of Trees|meta-tree|meta-trees','tree of trees · coined by this model','Collapse each tree to a point and connect them by “whose pain did you grow from” — a larger tree. It maps not code structure but the system’s growth history.');
defTerm('meta-root|meta-roots|Meta-root','meta root · coined by this model','The root of the tree of trees: the product’s first-principle assumption. Only one qualification: a dense enough run of one-way-door decisions. Seven paths, five meta-roots — the tool’s is deep editing, the SaaS’s being online together, the enterprise’s accountability, the consumer app’s data decides; the block family’s is the outward contract (Terraform’s declaration, Playwright’s promise; Sentry is the control group — convention before contract, the contract waking a day later, but the doors welded outside the ring all the same). Everything after grows on the terrain it welded shut.');
defTerm('first-principle assumption|first principle','first-principle assumption','The premise a product takes as true from day one and never debates. Written in no document, it decides where every tree grows — replacing it means rewriting the system.');
defTerm('one-way door|one-way doors|two-way door|two-way doors|one-way-door','one-way / two-way door · Bezos’s decision taxonomy','A two-way-door mistake can be walked back; a one-way door, once through, is nearly irreversible — file formats, the first table’s primary key, event-stream definitions, the promise that every step leaves a trail. Only a tree dense in one-way doors qualifies as meta-root; gating is the standard two-way door (a flag is born to be rolled back), so however early it grows, it defines no terrain.');
defTerm('path dependence','path dependence','A system’s present shape is decided by its historical order: trees that grow first define the terrain, and latecomers route around it. The same capabilities, acquired in a different order, make an entirely different system.');
defTerm('SLA|SLAs','Service Level Agreement','An availability promise written into the contract (99.95% a year, say), paid for in real money. Once an SLA is signed, fault tolerance and observability stop being engineering virtues and become financial obligations.');
defTerm('change window|change windows','change window','The fixed time slots in which changes may go live (usually off-peak or quarter-end); outside them the system is frozen. Release here is not a technical act but an approval process — gating grown into procedure rather than switch.');
defTerm('underground economy','the underground economy','The grey-and-black industry that monetizes your product: fake traffic, bonus farming, account theft, cash-out schemes. It arrives the moment the money does — a consumer product’s security apparatus (risk control, anti-abuse) is mostly extracted by it.');
// —— Block-path terms (Path E · Terraform) ——
defTerm('Hyrum\'s Law|Hyrum’s Law|Hyrum','Hyrum\'s Law','With enough users of an API, every observable behavior — documented or not — will eventually be depended on by somebody. A published contract thus becomes the hardest one-way door of all, welded by hands outside the ring.');
defTerm('state file|tfstate|terraform.tfstate','terraform.tfstate','Terraform’s snapshot of “the world as it stands”: a plan is the diff between your declaration and it. It is the product’s jugular — locking, drift, plaintext secrets, even the billing unit all grow on this one file.');
defTerm('plan|apply','plan & apply','Terraform’s heartbeat: first plan the diff of “what is about to happen”, have a human review it, then apply for real. The plan is a born gate — preview as approval.');
defTerm('provider|providers','Terraform cloud adapter plugin','The plugin that translates declared resources into concrete cloud API calls — and shields the engine from each cloud’s quirks (retries, waits, rate limits). Split out of the main repo in 2017 into its own ecosystem: the block’s second outward contract.');
defTerm('HCL','HashiCorp Configuration Language','Terraform’s declarative configuration language. Version 0.12 (2019) took two years to rewrite it as HCL2, with painful community migration — language semantics are among the earliest one-way doors welded shut.');
defTerm('BSL','Business Source License','A “source visible, commercial competition restricted” license. In 2023 HashiCorp moved Terraform from open-source MPL to BSL — which amounted to moving the ecosystem’s root.');
defTerm('OpenTofu','Terraform’s community fork','The open-source fork the community produced within a month of the BSL event, now under the Linux Foundation. Footnote: state encryption, which the open-source core never shipped, was delivered first by post-fork OpenTofu (1.7, 2024).');
defTerm('RUM','Resources Under Management','Terraform Cloud’s billing unit since 2023: you pay per resource under management — the billing unit is the number of entries in the state file; the business model grows on the data model.');
// —— Block-path terms (Path F · Playwright / Path G · Sentry) ——
defTerm('auto-wait','actionability waiting','Playwright’s default semantics: click doesn’t click at once — it first waits for the element to be visible, stable, and able to receive events. Twenty years of flaky-test experience compressed into an API default: the industrialization of tacit knowledge.');
defTerm('flaky|flaky test|flaky tests','flaky test','A test that passes and fails on different runs with no code change — timing, animation, network jitter are the usual culprits. Every cure for it is experience earned by stepping on rakes, not logic derived from first principles.');
defTerm('Trace Viewer|Trace','execution trace replay','Playwright packs a test’s complete scene — screenshots, DOM, network, console — into a trace file for step-by-step replay afterwards. The final answer to “works on my machine”.');
defTerm('grouping fingerprint|grouping algorithm|grouping convention','grouping fingerprint','What Sentry uses to decide “which events count as the same problem” — the heaviest one-way door of the convention: nudge the algorithm and every user’s issue history reshuffles; eventually the algorithm itself had to carry a version number.');
defTerm('Snuba','Sentry’s homegrown query layer','The 2019 service that moved event search and aggregation onto the columnar database ClickHouse — general-purpose databases couldn’t stand the event flood: performance here is not faith, it’s the bill.');
defTerm('source map|source maps','source map','The mapping file that locates a minified JS error back in the original source. Sentry must serve this kind of “stack dialect” for dozens of languages — spec explosion as daily life.');
defTerm('FSL','Functional Source License','The license Sentry invented in 2023: restricts competition, then auto-converts to open source after two years. The other ending for moving your root — no fork happened, because the real one-way doors live in the convention and the SDK network, not the license.');
defTerm('SDK|SDKs','Software Development Kit','The collection-and-integration code embedded in users’ applications. Sentry’s SDK matrix spans dozens of languages — each one a contract welded into someone else’s app, where changing the protocol means waiting for the world to upgrade.');
// —— Blender / VS Code domain terms ——
defTerm('sandbox|plugin sandbox','sandbox','A restricted runtime: plugins inside may use only explicitly granted capabilities, preventing unauthorized access to the host program or user data.');
defTerm('extension host','extension host','VS Code’s dedicated process for running extensions: all plugins live inside it, so a crashing plugin cannot drag down the editor itself.');
defTerm('extension point|extension points|extension-point registry','extension point','The plugin system’s registry of “where things may be plugged in”: menus, commands, panels — every mount point registers here. It and the plugin API are two halves of one mechanism.');
defTerm('dependency graph','dependency graph','The graph of “whose result depends on whom”. Blender uses it to decide, after you change one property, what needs recomputation and in what order.');
defTerm('scene graph','scene graph','The hierarchical organization of objects in 3D and document software: parent-child relations and transform inheritance hang on this tree. Move the parent and the children follow — that’s the scene graph at work.');
defTerm('modifier stack','modifier stack','Blender’s concept: a column of non-destructive modifications stacked on an object, applied in order, reorderable and removable at any time, with the original data always preserved.');
defTerm('gizmo|Gizmo|gizmos','viewport manipulator','The 3D handles you drag objects with in the viewport — move arrows, rotate rings, scale cubes. Where it appears and what it operates on is decided entirely by the current selection set.');
defTerm('selection set','selection set','The set of currently selected objects. Nearly every edit command takes it as input — the one answer to “what does this operation act on”.');
defTerm('viewport|Viewport','viewport','The live-rendered view of the scene. It is not an independent image but a projection of the underlying data: the data changes, and the picture must repaint.');
defTerm('undo stack|Undo stack|undo / redo stack','undo stack','The structure recording every operation in order, powering undo/redo. Every new command must answer “how do I undo myself” — which is why it mirrors the command system.');
defTerm('macro recording|macro','macro recording','Recording a user’s sequence of operations for later replay. Anything in the recording that referenced “the environment at the time” (an experiment branch, say) may no longer exist at replay.');
defTerm('non-destructive editing|Non-destructive editing','non-destructive editing','Edits never touch the original data; effects exist as stackable, undoable layers. The price: references to the original data are kept alive — which is how permission filtering can get bypassed.');
defTerm('datablock|datablocks','datablock','Blender’s unit of data: meshes, materials, scenes are all datablocks, cross-referenced by unique IDs, with refcounts deciding what gets saved and what becomes an “orphan” to be purged — the document model’s civil registry.');
defTerm('drivers|Drivers','driver (Blender)','Letting one property’s value be driven live by an expression or another property — bone rotation driving a mouth open, say. It silently writes values deep in the data model: an “invisible writer” the dependency graph must understand.');
defTerm('version migration|file-format migration','version migration','The logic that upgrades old-version files or data to the new structure. It must recognize every historical version forever — each format change adds one more era to its burden.');
defTerm('layout persistence','layout persistence','Saving the user’s panel positions and window splits to restore next launch. Where it is stored — and with which file — decides what it gets entangled with.');
